theme: minima
title: Harrison Wong
author: Harrison Wong
email: hello@harrisonjwong.com

twitter_username: harrisonjwong
github_username: harrisonjwong
linkedin_username: harrisonjwong

header_pages: 
  - contact.md
