theme: minima
title: Harrison Wong

twitter_username: harrisonjwong
github_username: harrisonjwong
linkedin_username: harrisonjwong

description: Hello

header_pages: 
  - projects.md
  - resume.md
  - contact.md
