theme: minima
title: Harrison Wong

twitter_username: harrisonjwong
github_username: harrisonjwong
linkedin_username: harrisonjwong

header_pages: 
  - projects.md
  - resume.md
  - interests.md
  - contact.md
  
  description: 
